### ISSUE TITLE
Uncaught URIError: URI malformed 

### ISSUE THREAD

**Issue by Pixeladed** [43081j/id3#22]
With some files it return this error to the console

Here's one of the file that got the error: http://www.mediafire.com/listen/13evge2b3nw5l1o/Muzzy_Insignia.mp3

**Comment by camikazegreen** [comment]
I am having the same issue with an album "Putumayo Presents Acoustic Café"
It is caused by the special character é, and if replaced with a regular e it works fine.

I'm using the minified library, but it is breaking on this line where 'n' is the album title: 
```javascript
if (a) {
            return new Buffer(n).toString()
        } else {
            return decodeURIComponent(escape(n))
        }
```
The escape is encoding the é as %E9 (Unicode) and the decodeURIComponent only works on UTF-8 characters.

**Comment by chrisrhoden** [comment]
I saw this with an MP3 that had an image encoded in it, specifically http://traffic.libsyn.com/thefeed/003_thefeed.mp3

What is the purpose of this roundtrip?

**Comment by gbiryukov** [comment]
You can use this fork https://github.com/gbiryukov/id3
This error fixed
To use as bower dependency, add to you bower.json dependencies: 
"id3": "https://github.com/gbiryukov/id3.git#1.1.4"

**Comment by vellaggio** [comment]
Hey, I've fixed this problem by replacing escape function for encodeURIComponent.

So instead of decodeURIComponent(escape(n)) --> decodeURIComponent(encodeURIComponent(n))
